services:
  db:
    image: pgduckdb/pgduckdb:18-v1.1.1
    container_name: praktikum-db-02-base
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - pgdata_02_base:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

volumes:
  pgdata_02_base:
    name: praktikum-db-02-base-pgdata
